name: AI-LAB train model
on:
  workflow_dispatch:
    inputs:
      from:
        description: "fastapi"
        required: true
        default: "fastapi"
      info:
        description: "Start Model Training"
        required: false

jobs:
  train:
    runs-on: self-hosted
    timeout-minutes: 10080
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: AI-LAB Train model
        run: sbatch --output=training_output.txt RL/DQN/run.sh
      - name: Wait for model file to appear
        run: |
          echo "Waiting for model file to be created: dqn_model.pth..."
          file_path="/ceph/project/charge_buddy/actions-runner/_work/ev_charge_api/ev_charge_api/dqn_model.pth"
          max_checks=10080  # Wait up to 7 days (10080 minutes)
          checks=0

          while [ ! -f "$file_path" ]; do
            checks=$(expr $checks + 1)

            if [ "$checks" -ge "$max_checks" ]; then
              echo "Timeout reached waiting for dqn_model.pth."
              exit 1
            fi

            echo "Model file not found yet (check ${checks}/${max_checks}). Sleeping 60s..."
            sleep 60
          done

          echo "Model file detected. Proceeding."
      - name: Archive model
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: /ceph/project/charge_buddy/actions-runner/_work/ev_charge_api/ev_charge_api/dqn_model.pth
      - name: Archive train_progress (if not finished)
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: /ceph/project/charge_buddy/actions-runner/_work/ev_charge_api/ev_charge_api/train_progress
      - name: Archive temp model (if not finished)
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: /ceph/project/charge_buddy/actions-runner/_work/ev_charge_api/ev_charge_api/dqn_model_temp.pth
      - name: Print Results
        run: echo /ceph/project/charge_buddy/actions-runner/_work/ev_charge_api/ev_charge_api/training_output.txt 
