name: AI-LAB train model
on:
  push:
    paths:
      - models/**
jobs:
  train:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install virtualenv
        run: srun singularity exec /ceph/container/python/python_3.10.sif pip install --user virtualenv
      - name: Make virtualenv
        run: srun singularity exec /ceph/container/python/python_3.10.sif ~/.local/bin/virtualenv ~/my-virtual-env
      - name: Install requirements
        run: srun singularity exec --bind ~/my-virtual-env:/my-virtual-env /ceph/container/python/python_3.10.sif /bin/bash -c "source /my-virtual-env/bin/activate && python3 -m pip install -r requirements.txt"
      - name: Submit sbatch job
        run: |
              sbatch --output=training_output.txt models/run.sh
              JOB_ID=$(sbatch models/run.sh | awk '{print $4}')
              echo "Submitted sbatch job with ID: $JOB_ID"
              echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV
      - name: Wait for sbatch job to finish
        run: |
          # Wait for the sbatch job to finish by checking its status
          while true; do
            JOB_STATUS=$(squeue --job $JOB_ID --noheader --format=%T)
            if [[ "$JOB_STATUS" == "COMPLETED" ]]; then
              echo "Job $JOB_ID completed successfully!"
              break
            elif [[ "$JOB_STATUS" == "FAILED" || "$JOB_STATUS" == "CANCELLED" ]]; then
              echo "Job $JOB_ID failed or was cancelled."
              exit 1
            fi
            echo "Job $JOB_ID is still running. Waiting..."
            sleep 60  # Wait 1 minute before checking again name: Archive model
      - uses: actions/upload-artifact@v4
        with:
          name: model
          path: /ceph/project/charge_buddy/actions-runner/_work/ev_charge_api/ev_charge_api/models/dqn_model.pth


