name: AI-LAB train model
on:
  push:
    paths:
      - models/**
jobs:
  train:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: AI-LAB Train model
        run: sbatch --output=training_output.txt models/run.sh



