name: AI-LAB train model
on:
  workflow_dispatch:
    inputs:
      from:
        description: "fastapi"
        required: true
        default: "fastapi"
      info:
        description: "Start Model Training"
        required: false

jobs:
  train:
    runs-on: self-hosted
    timeout-minutes: 10080
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: AI-LAB Train model
        run: sbatch --output=training_output.txt RL/DQN/run.sh
      - name: Check if there are jobs in the queue
        run: |
          echo "Waiting for no jobs in Slurm queue (two consecutive checks)..."
          consecutive_empty_checks=0

          while true; do
            jobs_in_queue=$(squeue --me | grep -v 'JOBID' | wc -l)

            if [ "$jobs_in_queue" -eq 0 ]; then
              ((consecutive_empty_checks++))
              echo "No jobs in the queue (check $consecutive_empty_checks/2)."
              if [ "$consecutive_empty_checks" -ge 2 ]; then
                echo "No jobs detected in two consecutive checks. Continuing."
                break
              fi
            else
              echo "There are $jobs_in_queue jobs in the queue. Waiting..."
              consecutive_empty_checks=0
            fi

            sleep 60  # Wait 60 seconds before checking again
          done
      - name: Archive model
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: /ceph/project/charge_buddy/actions-runner/_work/ev_charge_api/ev_charge_api/dqn_model.pth
      - name: Print Results
        run: echo /ceph/project/charge_buddy/actions-runner/_work/ev_charge_api/ev_charge_api/training_output.txt 
