name: AI-LAB train model
on:
  push:
    paths:
      - models/**
      - .github/workflows/ailab.yml
jobs:
  train:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install virtualenv
        run: srun singularity exec /ceph/container/python/python_3.10.sif pip install --user virtualenv
      - name: Make virtualenv
        run: srun singularity exec /ceph/container/python/python_3.10.sif ~/.local/bin/virtualenv ~/my-virtual-env
      - name: Install requirements
        run: srun singularity exec --bind ~/my-virtual-env:/my-virtual-env /ceph/container/python/python_3.10.sif /bin/bash -c "source /my-virtual-env/bin/activate && python3 -m pip install -r requirements.txt"
      - name: AI-LAB Train model
        run: sbatch --output=training_output.txt models/run.sh
      - name: Check if there are jobs in the queue
        run: |
          echo "Waiting for no jobs in Slurm queue..."
          while true; do
            # Check for jobs in the queue using squeue
            jobs_in_queue=$(squeue --me | grep -v 'JOBID' | wc -l)
            if [ "$jobs_in_queue" -eq 0 ]; then
              echo "No jobs in the queue. Continuing."
              break
            else
              echo "There are $jobs_in_queue jobs in the queue. Waiting..."
              sleep 60  # Wait 60 seconds before checking again
            fi
          done
      - name: Archive model
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: /ceph/project/charge_buddy/actions-runner/_work/ev_charge_api/ev_charge_api/models/dqn_model.pth


