name: AI-LAB test job
on:
  push:
jobs:
  test-hpc:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: AI-LAB Train model
        run: sbatch --output=hostname_output.txt models/t.sh



