[package]
name = "rl_scheduling"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
fxhash = "0.2.1"
pyo3 = { version="0.24.0", features = ["extension-module"]}

[lib]
crate-type = ["cdylib"]